### ISSUE TITLE
Australian Transport Card - Go Card (Queensland/Brisbane) support

### ISSUE THREAD

**Issue by andymac4182** [codebutler/farebot#10]
Hi, 

Not sure how but it would be great if support for the Go Card was added. Not sure exactly how to do this? If someone could either add support or let me know how to that would be great. :)

http://en.wikipedia.org/wiki/Go_card

Kind Regards,
Andrew

**Comment by andrewpollock** [comment]
I believe I have a decrypted dump of a Go card, if it's of any help with the task, I can make it available. I'm also prepared to put a bounty on this feature request.

**Comment by juanmackie** [comment]
@andrewpollock I too will add some $$ to the bounty !

**Comment by micolous** [comment]
I recently visited Brisbane (again), and now have two Go cards (Card A and Card B), and a third which belonged to someone else (Card C).  Cards A and C I was able to break the keys on.  Card B I was not able to break the keys on.  Each card has different keys for each sector of each card.

Unfortunately Card A is expired, and I don't know the balance of it, and Translink's website is not helpful in getting this information.  I made detailed records for Card B, but have been unable to access the data on the card.  Card C I do not have transaction logs for.

This is the state of play:

* Go cards have unique keys for every card as a (secret) function of their UID and their sector number.  This function is unknown, but the key is breakable by other methods.  No two cards have the same keys.

* Go cards have no open sectors on the card.  You must break the keys for each card in order to read them.  This means it's support will be like the other cards which require keys loaded in.

* This itself wouldn't be a problem, because of "mfcuk" and "mfoc", which take about 1.5 hours per card to break Mifare Classic keys.  [The hardware for this costs 40 USD](https://www.adafruit.com/products/364) plus [USB-UART adapter](https://www.adafruit.com/products/70) and shipping.  mfcuk is quite tedious to get running.

  * Before looking at the Go card, I never bothered to purchase hardware that can be used for key breaking. This has opened up many possibilities with working with the other, "easier" cards.

* Unfortunately, Mifare Classic has a _new_ series of card which fixes the "mfcuk" exploit vector. _Translink seem to have rolled these out starting somewhere between April and July 2015._  I think the way you can easily tell is the "Light Rail" icon on the reverse side has been added for Go cards.

What this means for you, the _end user_:

* In their current state, **Go cards will not be "universally readable" any time soon**.  You will need to break the keys on your card, this means buying or borrowing the hardware from someone else.  You can't use your phone to do this.

* As post-April 2015 cards proliferate, these will be resistant to key attacks, until a new attack is made.  **Only old cards can have the keys broken.**

* I have some support for Go cards in my branch `micolous/farebot@gocard`, but this is not in a nice state (and not in the Play Store version).  This requires encryption keys.  I can read the card number.  I can't make a lot of meaningful progress on Go cards, so I'm going to prioritise other, easier cards.

If you have complete dumps of the card that you've made with mfoc and a transaction log of what is on that card, I can use this information to improve the decoder.  Without this information I'm currently stuck.

**Comment by micolous** [comment]
I've implemented support for Go card in [my fork](https://github.com/micolous/farebot) which is [available in the Play Store](https://play.google.com/store/apps/details?id=au.id.micolous.farebot).

Encryption keys are needed to read the card.  These are different for every card.  You'll need to crack using an NFC transceiver device attached to your computer (not your phone) and software on your computer (mfcuk and mfoc).  It is not possible to crack it with your phone.

I still need help identifying station IDs, as there are about 8 known stations at present.  I do not live in Brisbane, and my working Go card is Mifare Plus so I don't have the ability to do this myself.

They don't seem to match up with any other database of stops which Translink published.

**Comment by codebutler** [comment]
Hi everyone, this code has been merged and will be available in the next release.  Thanks @micolous for all the work on this!

If you'd like earlier access please join the beta: https://play.google.com/apps/testing/com.codebutler.farebot
